CREATE DATABASE taskapp;

CREATE TABLE taskapp.tasks(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  status VARCHAR(100) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
